### PR TITLE
Hackathon Responsive UI

### PR DESCRIPTION
**Pull request by dadatuputi**
Changes:

- Changes to classes (Tailwind CSS) and in a few instances HTML structure to responsively display according to screen width
- Improved the menu so visible buttons would collapse into the dropdown on narrow screens
- Emoji picker also modified on narrow screens so it fits on the screen

Tested using Chrome and Firefox dev tools for mobile UIs. I couldn't test on an actual phone due to xxDK not working when proxying server ports.

### CODE REVIEW

**Comment by dadatuputi** [comment]
The reason I added `lucide-react` is the favorite star looked a bit funny from fontawesome, and apparently the only way to get it unfilled is to buy pro. I think lucide star looks better, and it's easier to modify.

**Comment by rcarback** [comment]
`lucide-react` is a decent add. I have no objections overall, except to make sure it's run through prettier and that lint and we test it thoroughly. 

Please see my other PR back into your branch: https://github.com/dadatuputi/haven/pulls

All I did here was:

```
npx prettier . --write
npm run lint
```

and fix the errors identified.

Also, I deployed that code on ICP here for testing: https://lbwo7-naaaa-aaaao-a3tha-cai.icp0.io/

**Comment by dadatuputi** [comment]
I ran into prettier on my PR #2 - when I went to deploy using Docker it complained. Looking at your PR.

Edit - looks good - merged. I merged the changes into my PR #2

**Comment by dadatuputi** [comment]
@rcarback This last commit disables a redirect for mobile devices, which will allow testing from phones.

**Comment by keithatxxdotnetwork** [comment]
Trace from Safari browser on iOS device
[haven-reactui-ios-safari.log](https://github.com/user-attachments/files/17613150/haven-reactui-ios-safari.log)

**Comment by dadatuputi** [comment]
Was that from Safari's private browsing mode @keithatxxdotnetwork ?

**Comment by keithatxxdotnetwork** [comment]
> Was that from Safari's private browsing mode @keithatxxdotnetwork ?

No, just opened the browser and pointed it to the URL. I believe the browser settings were all default.

**Pull request merged**
